### ISSUE TITLE
[STORY 2.2] User Login

### ISSUE THREAD

**Issue by catapam** [catapam/coffe-hub#14]
As a user, I want to log in to my account so that I can access my portfolio.

### Acceptance Criteria:
- [x] Login form includes fields for email and password.
- [x] Successful login redirects user to the dashboard.
- [x] Error message displayed for incorrect credentials.

### Tasks:
- [x] #79
- [x] #80
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [x] #85
- [x] #86
- [x] #87

### Linked Issues:
- #2 
- Documentation

##### Next story:
- #15 

##### Previous story:
- #13
