### ISSUE TITLE
[STORY 2.3] Password Management

### ISSUE THREAD

**Issue by catapam** [catapam/coffe-hub#15]
As a user, I want to reset my password if I forget it so that I can regain access to my account.

### Acceptance Criteria:
- [x] Forgot password link on the login page
- [x] Password reset email sent to the user.
- [x] User can set a new password using the link in the email.

### Tasks:
- [x] #88
- [x] #89
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #96

### Linked Issues:
- #2  
- Documentation: Password Reset Process Documentation

##### Next story:
- #16 

##### Previous story:
- #14
