### ISSUE TITLE
[STORY 4.3] Display payment feedback to users

### ISSUE THREAD

**Issue by catapam** [catapam/coffe-hub#25]
As a user, I want to receive feedback after making a payment so that I know if my purchase was successful or if there was an issue.

#### Acceptance Criteria:
- [x] Success message is shown after successful payment.
- [x] Error message is displayed if the payment fails.
- [x] Users can view order summary on the confirmation page.
- [ ] Option to retry payment in case of failure.

#### Tasks:
- [x] #146
- [x] #147
- [x] #148
- [x] #149
- [x] #150

#### Linked Issues:
- #4 
- Documentation: Payment Feedback Implementation

##### Next story:
- #26 

##### Previous story:
- #24
